---
kind: pipeline
name: Image Builder
platform:
  os: linux
  arch: amd64
steps:
  - name: pre-build Discord Notification Production
    image: appleboy/drone-discord
    when:
        branch: [16.0, 17.0, 18.0, main, master]
    settings:
      webhook_id:
        from_secret: webhook_id
      webhook_token:
        from_secret: webhook_token
      message: >
        _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
      
        ## 🦊 __**O17E - MaxMara**__
        
        🚀 Deploying **{{commit.branch}}** branch to production...

  - name: pre-build Discord Notification Test
    image: appleboy/drone-discord
    when:
        branch:
          exclude: [16.0, 17.0, 18.0, main, master]
    settings:
      webhook_id:
        from_secret: webhook_id
      webhook_token:
        from_secret: webhook_token
      message: >
        _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
        
        ## 🦊 __**O17E - MaxMara**__
        
        🔄 Deploying changes from **{{commit.branch}}** on test image...

#  - name: ssh-key
#    image: alpine
#    pull: always
#    environment:
#      SSH_FAST_API:
#        from_secret: ssh_fast_api
#    commands:
#      - echo "Generating ssh key..."
#      - mkdir -p /drone/src/.ssh
#      # Add as many as you need
#      - echo "$${SSH_FAST_API}" | tr -d '\r' > /drone/src/.ssh/id_<module_name>

  - name: publish-o-maxmara
    image: plugins/docker
    when:
      branch: [16.0, 17.0, 18.0, main, master]
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      registry: reg.bdr.group
      username:
        from_secret: reg_bdr_user
      password:
        from_secret: reg_bdr_password
      repo: reg.bdr.group/maxmara
      tags: 17
      dockerfile: Dockerfile
      build_args:
#        - ODOO_VERSION=reg.bdr.group/maxmara:17
        - BRANCH=${DRONE_BRANCH}

  - name: publish-o-maxmara-test
    image: plugins/docker
    when:
      branch:
        exclude: [16.0, 17.0, 18.0, main, master]
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      registry: reg.bdr.group
      username:
        from_secret: reg_bdr_user
      password:
        from_secret: reg_bdr_password
      repo: reg.bdr.group/maxmara
      tags: test
      dockerfile: Dockerfile
      build_args:
        - ODOO_VERSION=reg.bdr.group/maxmara:17
        - BRANCH=${DRONE_BRANCH}

  - name: image_update Production Server
    image: appleboy/drone-ssh
    when:
      branch: [16.0, 17.0, 18.0, main, master]
    settings:
      host:
        - 172.30.1.30
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_private_key
      port: 22
      command_timeout: 10m
      script:
        - ./image_update.sh

  - name: image_update Test Server
    image: appleboy/drone-ssh
    when:
      branch:
        exclude: [16.0, 17.0, 18.0, main, master]
    settings:
      host:
        - 172.30.1.30
      username:
        from_secret: ssh_username
      key:
        from_secret: ssh_private_key
      port: 22
      command_timeout: 10m
      script:
        - ./image_update/maxmara.sh

  - name: post-build Discord Notification
    image: appleboy/drone-discord
    when:
      status: [ success, failure, canceled, killed ]
    depends_on: []
    settings:
      webhook_id:
        from_secret: webhook_id
      webhook_token:
        from_secret: webhook_token
      message: >
        {{#success build.status}} 💿 🔼 Image update completed. {{/success}}
        {{#failure build.status}} ❌ 💿 Image update failed. {{/failure}}


  - name: post-image Discord Notification
    image: appleboy/drone-discord
    when:
      status: [success, failure, canceled, killed]
    depends_on: []
    settings:
      webhook_id:
        from_secret: webhook_id
      webhook_token:
        from_secret: webhook_token
      message:  >
        ### 🛠️ __**Build Status:**__ 🛠️

        {{#success build.status}} ✅ *Successful* {{/success}}
        {{#failure build.status}} ❌ *Failed* {{/failure}}
        
        
        🔍 **Triggered by:** {{commit.author}}

        🕒 **Total Time:** some minutes...(?)

        📂 **Branch:** {{commit.branch}}

        📝 **Commit:** {{commit.message}}
        
                                       _ MAXMARA _        
        _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 