[options]
addons_path =
 /usr/lib/python3/dist-packages/odoo/addons,
; /mnt/OCA ...
; /mnt/BDR ...
; /mnt/enterprise,
 /mnt/extra-addons
csv_internal_sep = ,
data_dir = /var/lib/odoo

db_host = pg15
db_password = odoo
db_port = 5432
db_user = odoo

; db_name = <client.bdr.group>
dbfilter = %d
; list_db = False

limit_time_cpu = 6000
limit_time_real = 9000

log_db = True
log_db_level = warning
log_handler = :INFO
log_level = info

gevent_port = 8072
proxy_mode = True
reportgz = False
server_wide_modules = base,web

workers = 2