apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "odoo.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "odoo.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "odoo.name" . }}
    spec:
      containers:
        - name: odoo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            {{- range .Values.ports }}
            - containerPort: {{ .containerPort }}
              name: {{ .name }}
            {{- end }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - >
                  until pg_isready -h {{ .Values.postgres.host }} -p {{ .Values.postgres.port }} -U {{ .Values.postgres.user }};
                  do echo "Waiting for postgres..."; sleep 2; done
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "odoo.fullname" . }}-pvc
