apiVersion: v1
kind: Service
metadata:
  name: {{ include "odoo.fullname" . }}
spec:
  selector:
    app: {{ include "odoo.name" . }}
  ports:
    {{- range .Values.ports }}
    - name: {{ .name }}
      port: {{ .containerPort }}
    {{- end }}