apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: odoo
          image: reg.bdr.group/maxmara:test
#          command: [ "odoo" ]
#          args:
#            - "--config=/mnt/odoo.conf"
          ports:
            - containerPort: 8069
            - containerPort: 8072
          env:
            - name: HOST
              value: postgres
            - name: PORT
              value: "5432"
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: odoo-db
                  key: POSTGRES_USER
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: odoo-db
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: odata
              mountPath: /var/lib/odoo
      volumes:
        - name: odata
          persistentVolumeClaim:
            claimName: odata