apiVersion: v1
kind: Service
metadata:
  name: odoo-svc
spec:
  selector:
    app: odoo
  ports:
    - name: http
      port: 8069
      targetPort: 8069
    - name: longpoll
      port: 8070
      targetPort: 8072
  type: ClusterIP