apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
  namespace: dev-odoo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs