apiVersion: v1
kind: Secret
metadata:
  name: odoo-db
type: Opaque
stringData:
  POSTGRES_DB: odoo
  POSTGRES_USER: odoo
  POSTGRES_PASSWORD: odoo

---
apiVersion: v1
data:
  .dockerconfigjson: ++++++++
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: mxm:/Secret:odoo-test/regcred
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","data":{".dockerconfigjson":"eyJhdXRocyI6eyJyZWcuYmRyLmdyb3VwIjp7InVzZXJuYW1lIjoiYmRyIiwicGFzc3dvcmQiOiJPdUIxdlE1VHJDRCIsImVtYWlsIjoic29wb3J0ZUBiZHJpbmZvcm1hdGljYS5jb20iLCJhdXRoIjoiWW1SeU9rOTFRakYyVVRWVWNrTkUifX19"},"kind":"Secret","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"odoo-repo:/Secret:odoo-test/regcred"},"creationTimestamp":"2025-12-15T15:20:26Z","name":"regcred","namespace":"odoo-test","resourceVersion":"74058052","uid":"21d701f7-0724-47e5-bd00-0caff51d7742"},"type":"kubernetes.io/dockerconfigjson"}
  creationTimestamp: '2025-12-15T15:20:26Z'
  name: regcred
  namespace: odoo-test
  resourceVersion: '74059190'
  uid: 21d701f7-0724-47e5-bd00-0caff51d7742
type: kubernetes.io/dockerconfigjson