apiVersion: v2
name: maxmara-stack
version: 0.1.0
description: Helm chart for Maxmara + Postgres stack
dependencies:
  - name: postgres
    version: 0.1.0
    repository: "file://charts/postgres"
  - name: odoo
    version: 0.1.0
    repository: "file://charts/odoo"
