apiVersion: v2
name: maxmara-stack
version: 0.1.0
description: Helm chart for Maxmara + Postgres stack
dependencies:
  - name: postgresql
    version: 15.5.38
    repository: "https://charts.bitnami.com/bitnami"
