odoo:
  image: odoo:18.0
  replicas: 1
  service:
    type: ClusterIP
    port: 8069
    longpollPort: 8072
#  ingress:
#    enabled: true
#    className: nginx
#    host: odoo.example.com
#    tls: true
#    tlsSecretName: odoo-tls
  persistence:
    enabled: true
    storageClassName: rook-cephfs
    size: 10Gi
    accessModes: ["ReadWriteOnce"]
    mountPath: /var/lib/odoo
  extraAddons:
    enabled: true
    # If you mount extra addons via PVC/CSI/NFS etc.
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 2Gi

postgres:
  image: postgres:17
  service:
    port: 5432
  persistence:
    enabled: true
    storageClassName: rook-cephfs
    size: 10Gi
    accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 2Gi

db:
  name: odoo
  user: odoo
  # Testing purposes
  password: "odoo"
