postgresql:
  image:
    tag: "17"

  auth:
    username: odoo
    password: odoo
    database: odoo

  primary:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: ""

    extraEnvVars:
      - name: PGDATA
        value: /bitnami/postgresql/data/pgdata

odoo:
  image: reg.bdr.group/maxmara:18
  service:
    type: ClusterIP
    port8069: 8069
    port8072: 8072
  env:
    - name: ODOO_RC
      value: /mnt/odoo.conf
#  # You can configure odoo conf manualy here:
#  odooConf: |
#    [options]
#    ; add your config here
#    db_host = <chart-name>-postgresql
#    db_port = 5432
#    db_user = odoo
#    db_password = odoo
  persistence:
    enabled: true
    mountPath: /var/lib/odoo
    size: 10Gi
