postgresql:
  image:
    tag: "17"

  auth:
    username: odoo
    password: odoo
    database: odoo

  primary:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: ""

    extraEnvVars:
      - name: PGDATA
        value: /bitnami/postgresql/data/pgdata

odoo:
#  image: reg.bdr.group/maxmara:18
  image: odoo:18
  service:
    type: ClusterIP
    port8069: 8069
    port8072: 8072
  env:
    - name: ODOO_RC
      value: /mnt/odoo.conf
#  persistence:
#    enabled: true
#    mountPath: /var/lib/odoo
#    size: 10Gi
  persistence:
    accessModes:
      - ReadWriteOnce
    size: 20Gi
    storageClassName: ""
