apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
spec:
  ports:
    - port: 5432
  selector:
    app: {{ include "postgres.name" . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgres.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}