apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "odoo.fullname" . }}-conf
data:
  odoo.conf: |
{{- if eq .Values.environment "prod" }}
{{ .Files.Get "odoo.conf" | indent 4 }}
{{- else }}
{{ .Files.Get "staging-odoo.conf" | indent 4 }}
{{- end }}