apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-odoo
spec:
  replicas: {{ default 1 .Values.odoo.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-odoo
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-odoo
    spec:
      containers:
        - name: odoo
          image: {{ .Values.odoo.image | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8069
            - name: longpoll
              containerPort: 8072
          env:
            - name: ODOO_RC
              value: /mnt/odoo.conf
          volumeMounts:
            - name: odoo-data
              mountPath: /var/lib/odoo
            - name: odoo-conf
              mountPath: /mnt/odoo.conf
              subPath: odoo.conf
      volumes:
        - name: odoo-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-odoo-data
        - name: odoo-conf
          configMap:
            name: {{ include "odoo.fullname" . }}-conf
