apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-odoo-data
spec:
  accessModes:
{{ toYaml .Values.odoo.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.odoo.persistence.size | quote }}
  {{- if .Values.odoo.persistence.storageClassName }}
  storageClassName: {{ .Values.odoo.persistence.storageClassName | quote }}
  {{- end }}