apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image | quote }}
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: odoo-db
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
spec:
  accessModes: {{ toYaml .Values.postgres.persistence.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size | quote }}
  storageClassName: {{ .Values.postgres.persistence.storageClassName | quote }}