apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
spec:
  accessModes: {{ toYaml .Values.postgres.persistence.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size | quote }}
  storageClassName: {{ .Values.postgres.persistence.storageClassName | quote }}