apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: pg
      port: {{ .Values.postgres.service.port }}
      targetPort: 5432
  type: ClusterIP